-- SQLite: Step 1 Baseline
DROP TABLE IF EXISTS {{BASELINE_TABLE}};
CREATE TABLE {{BASELINE_TABLE}} AS
SELECT {{PK_COL_1}}, {{PK_COL_2}}, {{BIZ_COL_1}}, {{BIZ_COL_2}},
       {{BIZ_COL_3}}, {{BIZ_COL_4}}, {{BIZ_COL_5}}, {{BRANCH_COL}}
FROM {{OLD_SQL_OR_VIEW}};
