-- SQLite: Step 2 Sample
DROP TABLE IF EXISTS {{SAMPLE_TABLE}};
CREATE TABLE {{SAMPLE_TABLE}} AS
SELECT 'EXCEPTION' AS SAMPLE_TYPE, t.{{PK_COL_1}}, t.{{PK_COL_2}}
FROM {{SOURCE_TABLE}} t WHERE {{EXCEPTION_FILTER}} LIMIT 10;

INSERT INTO {{SAMPLE_TABLE}}
SELECT 'BOUNDARY', t.{{PK_COL_1}}, t.{{PK_COL_2}}
FROM {{SOURCE_TABLE}} t WHERE {{BOUNDARY_FILTER}} LIMIT 10;

INSERT INTO {{SAMPLE_TABLE}}
SELECT 'NORMAL', t.{{PK_COL_1}}, t.{{PK_COL_2}}
FROM {{SOURCE_TABLE}} t WHERE {{NORMAL_FILTER}} LIMIT 10;
