-- SQLite: Step 4 Diff Report (must return 0 rows)
SELECT SAMPLE_TYPE, {{PK_COL_1}}, {{PK_COL_2}}
FROM {{COMPARE_TABLE}}
WHERE COALESCE(CAST(OLD_{{BIZ_COL_1}} AS TEXT),'#') <> COALESCE(CAST(NEW_{{BIZ_COL_1}} AS TEXT),'#')
   OR COALESCE(OLD_{{BIZ_COL_2}},-1) <> COALESCE(NEW_{{BIZ_COL_2}},-1)
   OR COALESCE(OLD_{{BIZ_COL_3}},-1) <> COALESCE(NEW_{{BIZ_COL_3}},-1)
   OR ABS(COALESCE(OLD_{{BIZ_COL_4}},0) - COALESCE(NEW_{{BIZ_COL_4}},0)) > {{NUMERIC_TOL}}
   OR ABS(COALESCE(OLD_{{BIZ_COL_5}},0) - COALESCE(NEW_{{BIZ_COL_5}},0)) > {{NUMERIC_TOL}}
   OR COALESCE(OLD_{{BRANCH_COL}},'#') <> COALESCE(NEW_{{BRANCH_COL}},'#');
