-- SQLite: Step 5 Aggregate Check
WITH
old_stats AS (SELECT COUNT(*) CNT, SUM({{AMT_COL}}) SUM_AMT, SUM({{WEIGHTED_COL}}) SUM_WEIGHTED,
                     AVG({{RATIO_COL}}) AVG_RATIO, COUNT(DISTINCT {{GROUP_COL}}) GROUP_CNT FROM {{BASELINE_TABLE}}),
new_stats AS (SELECT COUNT(*) CNT, SUM({{AMT_COL}}) SUM_AMT, SUM({{WEIGHTED_COL}}) SUM_WEIGHTED,
                     AVG({{RATIO_COL}}) AVG_RATIO, COUNT(DISTINCT {{GROUP_COL}}) GROUP_CNT FROM {{NEW_SQL_OR_VIEW}})
SELECT 'CNT' AS METRIC, o.CNT AS OLD_VAL, n.CNT AS NEW_VAL, n.CNT-o.CNT AS DIFF,
       ROUND((n.CNT-o.CNT)*100.0/NULLIF(o.CNT,0),6) AS DIFF_PCT FROM old_stats o, new_stats n
UNION ALL
SELECT 'SUM_AMT', o.SUM_AMT, n.SUM_AMT, n.SUM_AMT-o.SUM_AMT,
       ROUND((n.SUM_AMT-o.SUM_AMT)*100.0/NULLIF(o.SUM_AMT,0),6) FROM old_stats o, new_stats n
UNION ALL
SELECT 'SUM_WEIGHTED', o.SUM_WEIGHTED, n.SUM_WEIGHTED, n.SUM_WEIGHTED-o.SUM_WEIGHTED,
       ROUND((n.SUM_WEIGHTED-o.SUM_WEIGHTED)*100.0/NULLIF(o.SUM_WEIGHTED,0),6) FROM old_stats o, new_stats n
UNION ALL
SELECT 'AVG_RATIO', o.AVG_RATIO, n.AVG_RATIO, n.AVG_RATIO-o.AVG_RATIO, NULL FROM old_stats o, new_stats n
UNION ALL
SELECT 'GROUP_CNT', o.GROUP_CNT, n.GROUP_CNT, n.GROUP_CNT-o.GROUP_CNT, NULL FROM old_stats o, new_stats n;
