-- SQLite: Step 6 Group Diff
SELECT o.{{GROUP_COL}} AS OLD_GROUP, n.{{GROUP_COL}} AS NEW_GROUP, COUNT(*) AS CHANGED_CNT
FROM {{BASELINE_TABLE}} o JOIN {{NEW_SQL_OR_VIEW}} n
  ON o.{{PK_COL_1}}=n.{{PK_COL_1}} AND o.{{PK_COL_2}}=n.{{PK_COL_2}}
WHERE COALESCE(o.{{GROUP_COL}},'#') <> COALESCE(n.{{GROUP_COL}},'#')
GROUP BY o.{{GROUP_COL}}, n.{{GROUP_COL}};
