-- Oracle: Step 1 Baseline Snapshot
-- 改 SQL 前必跑，作為驗收基準
DROP TABLE {{BASELINE_TABLE}} PURGE;
CREATE TABLE {{BASELINE_TABLE}} AS
SELECT {{PK_COL_1}}, {{PK_COL_2}}, {{BIZ_COL_1}}, {{BIZ_COL_2}},
       {{BIZ_COL_3}}, {{BIZ_COL_4}}, {{BIZ_COL_5}}, {{BRANCH_COL}}
FROM {{OLD_SQL_OR_VIEW}};
COMMIT;

SELECT COUNT(*) AS BASELINE_CNT FROM {{BASELINE_TABLE}};
