-- Oracle: Step 2 Golden Sample
DROP TABLE {{SAMPLE_TABLE}} PURGE;
CREATE TABLE {{SAMPLE_TABLE}} AS
SELECT * FROM (
    SELECT 'EXCEPTION' AS SAMPLE_TYPE, t.{{PK_COL_1}}, t.{{PK_COL_2}}
    FROM {{SOURCE_TABLE}} t WHERE {{EXCEPTION_FILTER}} AND ROWNUM <= 10
    UNION ALL
    SELECT 'BOUNDARY', t.{{PK_COL_1}}, t.{{PK_COL_2}}
    FROM {{SOURCE_TABLE}} t WHERE {{BOUNDARY_FILTER}} AND ROWNUM <= 10
    UNION ALL
    SELECT 'NORMAL', t.{{PK_COL_1}}, t.{{PK_COL_2}}
    FROM {{SOURCE_TABLE}} t WHERE {{NORMAL_FILTER}} AND ROWNUM <= 10
    UNION ALL
    SELECT 'NULL_CASE', t.{{PK_COL_1}}, t.{{PK_COL_2}}
    FROM {{SOURCE_TABLE}} t WHERE {{NULL_FILTER}} AND ROWNUM <= 5
);
COMMIT;
