-- Oracle: Step 5 Aggregate Check
WITH
old_stats AS (SELECT COUNT(*) CNT, SUM({{AMT_COL}}) SUM_AMT, SUM({{WEIGHTED_COL}}) SUM_WEIGHTED,
                     AVG({{RATIO_COL}}) AVG_RATIO, COUNT(DISTINCT {{GROUP_COL}}) GROUP_CNT FROM {{BASELINE_TABLE}}),
new_stats AS (SELECT COUNT(*) CNT, SUM({{AMT_COL}}) SUM_AMT, SUM({{WEIGHTED_COL}}) SUM_WEIGHTED,
                     AVG({{RATIO_COL}}) AVG_RATIO, COUNT(DISTINCT {{GROUP_COL}}) GROUP_CNT FROM {{NEW_SQL_OR_VIEW}})
SELECT 'CNT' METRIC, o.CNT OLD_VAL, n.CNT NEW_VAL, n.CNT-o.CNT DIFF,
       ROUND((n.CNT-o.CNT)/NULLIF(o.CNT,0)*100,6) DIFF_PCT FROM old_stats o, new_stats n
UNION ALL
SELECT 'SUM_AMT', o.SUM_AMT, n.SUM_AMT, n.SUM_AMT-o.SUM_AMT,
       ROUND((n.SUM_AMT-o.SUM_AMT)/NULLIF(o.SUM_AMT,0)*100,6) FROM old_stats o, new_stats n
UNION ALL
SELECT 'SUM_WEIGHTED', o.SUM_WEIGHTED, n.SUM_WEIGHTED, n.SUM_WEIGHTED-o.SUM_WEIGHTED,
       ROUND((n.SUM_WEIGHTED-o.SUM_WEIGHTED)/NULLIF(o.SUM_WEIGHTED,0)*100,6) FROM old_stats o, new_stats n
UNION ALL
SELECT 'AVG_RATIO', o.AVG_RATIO, n.AVG_RATIO, n.AVG_RATIO-o.AVG_RATIO, NULL FROM old_stats o, new_stats n
UNION ALL
SELECT 'GROUP_CNT', o.GROUP_CNT, n.GROUP_CNT, n.GROUP_CNT-o.GROUP_CNT, NULL FROM old_stats o, new_stats n;
